--- 
- name: Get VMs
  # hosts: localhost
  hosts: machines
  connection: local
  tasks:
    - name: include vars
      include_vars:
        dir: group_vars

    - name: Gather VM
      #vmware_guest_facts:
      vmware_guest_info:
        validate_certs: False
        hostname: '{{ site }}{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter: '{{ site }}{{ vcenter_datacenter }}'
        # name: "usrdavs012ccp8a" 
        name:  "{{ inventory_hostname }}"
        schema: "vsphere"
        properties: ["config.hardware.memoryMB", "guest.disk", "guest.net", "overallStatus"]
      delegate_to: localhost
      register: vminfo

    - debug:
        msg: "{{ vminfo }}"

    - name: Remove all snapshots of a VM
      vmware_guest_snapshot:
        hostname: "{{ site }}{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ site }}{{ vcenter_datacenter }}"
        # folder: "/{{ datacenter }}/"
        folder: "/"
        # name: usrdads022ccp8a 
        name:  "{{ inventory_hostname }}"
        state: remove_all
        validate_certs: False
      delegate_to: localhost
